export const kelimeEmoji: Record<string, string> = {
  kedi: "🐱",
  kopek: "🐶",
  at: "🐴",
  inek: "🐮",
  goyun: "🐑",
  keci: "🐐",
  tavuk: "🐔",
  horoz: "🐓",
  esek: "🫏",
  kurt: "🐺",
  rovsî: "🦊",
  xers: "🐻",
  mar: "🐍",
  masî: "🐟",
  çûçik: "🐦",
  kêzik: "🐛",
  hespê_avê: "🐸",
  mişk: "🐭",
  kêvroşk: "🐰",
  hirç: "🦔",

  kirmizi: "🔴",
  mavi: "🔵",
  sari: "🟡",
  yesil: "🟢",
  beyaz: "⚪",
  siyah: "⚫",
  turuncu: "🟠",
  mor: "🟣",
  pembe: "🩷",
  kahverengi: "🟤",
  gri: "🌫️",
  gumus: "🥈",

  bir: "1️⃣",
  iki: "2️⃣",
  uc: "3️⃣",
  dort: "4️⃣",
  bes: "5️⃣",
  alti: "6️⃣",
  yedi: "7️⃣",
  sekiz: "8️⃣",
  dokuz: "9️⃣",
  on: "🔟",
  onbir: "🔢",
  oniki: "🔢",
  onuc: "🔢",
  ondort: "🔢",
  onbes: "🔢",
  onalti: "🔢",
  onyedi: "🔢",
  onsekiz: "🔢",
  ondokuz: "🔢",
  yirmi: "🔢",

  elma: "🍎",
  muz: "🍌",
  uzum: "🍇",
  armut: "🍐",
  nar: "🍅",
  portakal: "🍊",
  limon: "🍋",
  kiraz: "🍒",
  seftali: "🍑",
  karpuz: "🍉",
  kavun: "🍈",
  dut: "🫐",
  kayisi: "🥭",
  cilek: "🍓",
  incir: "🌰",

  anne: "👩",
  baba: "👨",
  agabey: "👦",
  ablakizkardes: "👧",
  babaanne: "👵",
  dede: "👴",
  amca: "🧔",
  hala: "🧕",
  dayi: "🧔‍♂️",
  teyze: "👩‍🦰",
  kuzenerkek: "🧑",
  kuzenkiz: "👱‍♀️",
  cocuk: "🧒",
  ogul: "👦",
  kiz: "👧",

  ev: "🏠",
  kapi: "🚪",
  pencere: "🪟",
  masa: "🪵",
  sandalye: "🪑",
  yatak: "🛏️",
  cati: "🏚️",
  duvar: "🧱",
  salon: "🛋️",
  mutfak: "🍳",
  banyo: "🛁",
  oda: "🗝️",
  lamba: "💡",
  telefon: "☎️",
  televizyon: "📺",

  gunes: "☀️",
  ay: "🌙",
  yildiz: "⭐",
  gokyuzu: "🌌",
  bulut: "☁️",
  yagmur: "🌧️",
  kar: "❄️",
  ruzgar: "💨",
  simsek: "⚡",
  soguk: "🥶",
  sicak: "🥵",
  ilkbahar: "🌸",
  yaz: "🏖️",
  sonbahar: "🍂",
  kis: "⛄",

  ekmek: "🍞",
  su: "💧",
  sut: "🥛",
  peynir: "🧀",
  yumurta: "🥚",
  et: "🥩",
  pirinc: "🍚",
  un: "🌾",
  seker: "🍬",
  tuz: "🧂",
  cay: "🍵",
  kahve: "☕",
  bal: "🍯",
  corba: "🍲",
  pasta: "🍰",
};

export function getKelimeEmoji(id: string, fallback = "✨"): string {
  return kelimeEmoji[id] ?? fallback;
}

export const emojiByTr: Record<string, string> = {
  Kedi: "🐱",
  Köpek: "🐶",
  At: "🐴",
  İnek: "🐮",
  Koyun: "🐑",
  Keçi: "🐐",
  Tavuk: "🐔",
  Horoz: "🐓",
  Eşek: "🫏",
  Kurt: "🐺",
  Tilki: "🦊",
  Ayı: "🐻",
  Yılan: "🐍",
  Balık: "🐟",
  Kuş: "🐦",
  Böcek: "🐛",
  Kurbağa: "🐸",
  Fare: "🐭",
  Tavşan: "🐰",
  Kirpi: "🦔",

  Kırmızı: "🔴",
  Mavi: "🔵",
  Sarı: "🟡",
  Yeşil: "🟢",
  Beyaz: "⚪",
  Siyah: "⚫",
  Turuncu: "🟠",
  Mor: "🟣",
  Pembe: "🩷",
  Kahverengi: "🟤",
  Gri: "🌫️",
  Gümüş: "🥈",

  Bir: "1️⃣",
  İki: "2️⃣",
  Üç: "3️⃣",
  Dört: "4️⃣",
  Beş: "5️⃣",
  Altı: "6️⃣",
  Yedi: "7️⃣",
  Sekiz: "8️⃣",
  Dokuz: "9️⃣",
  On: "🔟",
  "On bir": "🔢",
  "On iki": "🔢",
  "On üç": "🔢",
  "On dört": "🔢",
  "On beş": "🔢",
  "On altı": "🔢",
  "On yedi": "🔢",
  "On sekiz": "🔢",
  "On dokuz": "🔢",
  Yirmi: "🔢",

  Elma: "🍎",
  Muz: "🍌",
  Üzüm: "🍇",
  Armut: "🍐",
  Nar: "🍅",
  Portakal: "🍊",
  Limon: "🍋",
  Kiraz: "🍒",
  Şeftali: "🍑",
  Karpuz: "🍉",
  Kavun: "🍈",
  Dut: "🫐",
  Kayısı: "🥭",
  Çilek: "🍓",
  İncir: "🌰",

  Anne: "👩",
  Baba: "👨",
  "Erkek kardeş": "👦",
  "Kız kardeş": "👧",
  Babaanne: "👵",
  Dede: "👴",
  Amca: "🧔",
  Hala: "🧕",
  Dayı: "🧔‍♂️",
  Teyze: "👩‍🦰",
  "Kuzen (erkek)": "🧑",
  "Kuzen (kız)": "👱‍♀️",
  Çocuk: "🧒",
  Oğul: "👦",
  Kız: "👧",

  Ev: "🏠",
  Kapı: "🚪",
  Pencere: "🪟",
  Masa: "🪵",
  Sandalye: "🪑",
  Yatak: "🛏️",
  Çatı: "🏚️",
  Duvar: "🧱",
  Salon: "🛋️",
  Mutfak: "🍳",
  Banyo: "🛁",
  Oda: "🗝️",
  Lamba: "💡",
  Telefon: "☎️",
  Televizyon: "📺",

  Güneş: "☀️",
  Ay: "🌙",
  Yıldız: "⭐",
  Gökyüzü: "🌌",
  Bulut: "☁️",
  Yağmur: "🌧️",
  Kar: "❄️",
  Rüzgar: "💨",
  Şimşek: "⚡",
  Soğuk: "🥶",
  Sıcak: "🥵",
  İlkbahar: "🌸",
  Yaz: "🏖️",
  Sonbahar: "🍂",
  Kış: "⛄",

  Ekmek: "🍞",
  Su: "💧",
  Süt: "🥛",
  Peynir: "🧀",
  Yumurta: "🥚",
  Et: "🥩",
  Pirinç: "🍚",
  Un: "🌾",
  Şeker: "🍬",
  Tuz: "🧂",
  Çay: "🍵",
  Kahve: "☕",
  Bal: "🍯",
  Çorba: "🍲",
  Pasta: "🍰",
};

export function getKelimeEmojiByTr(tr: string, fallback = "✨"): string {
  return emojiByTr[tr] ?? fallback;
}
